In [5]:
import numpy as np
a = np.random.random((2,6))
a

array([[0.53978079, 0.34278087, 0.32884599, 0.53782487, 0.6296689 ,
        0.27514543],
       [0.06583552, 0.72964363, 0.73639622, 0.11181871, 0.47076551,
        0.83932986]])

In [21]:
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
c = np.linspace(1,10,10)
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])