In [9]:
import numpy as np

iu1 = np.triu_indices(2)
iu1

(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64))

In [10]:
iu1 = np.triu_indices(3)
iu1

(array([0, 0, 0, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 1, 2, 2], dtype=int64))

In [11]:
iu1 = np.triu_indices(4)
iu1

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3], dtype=int64),
 array([0, 1, 2, 3, 1, 2, 3, 2, 3, 3], dtype=int64))

In [4]:

iu2 = np.triu_indices(4, 1)
iu2


(array([0, 0, 1], dtype=int64), array([2, 3, 3], dtype=int64))

In [5]:
iu2 = np.triu_indices(4, 2)
iu2

(array([0, 0, 0, 1, 1, 2], dtype=int64),
 array([1, 2, 3, 2, 3, 3], dtype=int64))

In [13]:
 a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
a[iu1]

array([ 0,  1,  2,  3,  5,  6,  7, 10, 11, 15])

In [16]:
a[iu1] = -1
a

array([[-1, -1, -1, -1],
       [ 4, -1, -1, -1],
       [ 8,  9, -1, -1],
       [12, 13, 14, -1]])

In [17]:
a[iu2] = -10
a

array([[ -1, -10, -10, -10],
       [  4,  -1, -10, -10],
       [  8,   9,  -1, -10],
       [ 12,  13,  14,  -1]])